"""
Sentry Stake IoT System Module

Low-cost CCTV-based IoT monitoring system for automated plant health surveillance.

Features:
- Edge AI processing on low-cost hardware
- NIR (850nm) and Red (660nm) LED synchronized flashing
- On-chip NDVI calculation and stress detection
- Mesh networking for multi-device deployments
- Solar/battery power management
- OTA firmware updates
- Automated time-series monitoring
- Real-time alerts and notifications

The Sentry Stake transforms affordable CCTV cameras into intelligent agricultural
monitoring devices with on-board multispectral sensing capabilities.
"""

import numpy as np
from typing import Dict, List, Tuple, Optional, Union, Any
from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import Enum
import json
import time


class DeviceStatus(Enum):
    """Device operational status."""
    OFFLINE = "offline"
    ONLINE = "online"
    IDLE = "idle"
    CAPTURING = "capturing"
    PROCESSING = "processing"
    LOW_BATTERY = "low_battery"
    ERROR = "error"
    UPDATING = "updating"


class PowerSource(Enum):
    """Power source types."""
    BATTERY = "battery"
    SOLAR = "solar"
    AC_ADAPTER = "ac_adapter"
    HYBRID = "hybrid"


class NetworkProtocol(Enum):
    """Network communication protocols."""
    WIFI = "wifi"
    LORA = "lora"
    ZIGBEE = "zigbee"
    BLUETOOTH = "bluetooth"
    CELLULAR = "cellular"


@dataclass
class SentryConfig:
    """Sentry device configuration."""
    device_id: str
    firmware_version: str
    
    # Imaging configuration
    resolution: Tuple[int, int] = (1920, 1080)
    frame_rate: int = 30
    
    # LED configuration
    nir_led_power: int = 100  # 0-100%
    red_led_power: int = 100
    flash_duration_ms: int = 100
    
    # Processing configuration
    ndvi_calculation_enabled: bool = True
    stress_detection_enabled: bool = True
    processing_interval_minutes: int = 60
    
    # Storage configuration
    local_storage_days: int = 7
    cloud_sync_enabled: bool = True
    
    # Power configuration
    power_source: PowerSource = PowerSource.HYBRID
    sleep_mode_enabled: bool = True
    low_power_threshold: float = 20.0
    
    # Network configuration
    network_protocol: NetworkProtocol = NetworkProtocol.WIFI
    mesh_enabled: bool = True
    
    # Alert configuration
    alert_threshold_ndvi: float = 0.4
    alert_threshold_stress: float = 0.7


@dataclass
class SentryMeasurement:
    """Single measurement from Sentry device."""
    timestamp: datetime
    device_id: str
    
    # Images
    nir_image: Optional[np.ndarray] = None
    red_image: Optional[np.ndarray] = None
    ambient_image: Optional[np.ndarray] = None
    
    # Calculated metrics
    ndvi_mean: Optional[float] = None
    ndvi_map: Optional[np.ndarray] = None
    stress_level: float = 0.0
    stress_map: Optional[np.ndarray] = None
    
    # Environmental
    temperature: Optional[float] = None
    humidity: Optional[float] = None
    light_intensity: Optional[float] = None
    
    # Device status
    battery_level: float = 100.0
    signal_strength: int = -50  # dBm
    
    metadata: Dict = None


@dataclass
class SentryAlert:
    """Alert generated by Sentry device."""
    alert_id: str
    timestamp: datetime
    device_id: str
    alert_type: str
    severity: str  # 'low', 'medium', 'high', 'critical'
    
    message: str
    ndvi_value: Optional[float] = None
    stress_level: Optional[float] = None
    
    location: Optional[Tuple[float, float]] = None
    image_url: Optional[str] = None
    
    acknowledged: bool = False
    resolved: bool = False


class SentryDevice:
    """
    Low-cost CCTV-based Sentry Stake device controller.
    
    Manages camera, LEDs, processing, and communication for automated
    plant health monitoring.
    """
    
    def __init__(
        self,
        device_id: str,
        config: Optional[SentryConfig] = None
    ):
        """
        Initialize Sentry device.
        
        Args:
            device_id: Unique device identifier
            config: Device configuration
        """
        self.device_id = device_id
        self.config = config or SentryConfig(
            device_id=device_id,
            firmware_version="1.0.0"
        )
        
        self.status = DeviceStatus.OFFLINE
        self.battery_level = 100.0
        self.last_measurement: Optional[SentryMeasurement] = None
        
        # Initialize components
        self.camera = self._initialize_camera()
        self.led_controller = LEDController(
            nir_power=config.nir_led_power if config else 100,
            red_power=config.red_led_power if config else 100
        )
        self.edge_processor = EdgeAIProcessor()
        
        # Measurement history
        self.measurement_history: List[SentryMeasurement] = []
        self.alert_queue: List[SentryAlert] = []
        
    def _initialize_camera(self) -> Dict:
        """Initialize camera interface."""
        return {
            'resolution': self.config.resolution,
            'frame_rate': self.config.frame_rate,
            'initialized': True,
            'last_capture': None
        }
    
    def start(self) -> bool:
        """Start Sentry device operation."""
        try:
            # Power on components
            self._power_on_camera()
            self.led_controller.initialize()
            
            # Set status
            self.status = DeviceStatus.IDLE
            
            print(f"[{self.device_id}] Sentry device started successfully")
            return True
            
        except Exception as e:
            print(f"[{self.device_id}] Error starting device: {e}")
            self.status = DeviceStatus.ERROR
            return False
    
    def stop(self) -> bool:
        """Stop Sentry device operation."""
        try:
            # Power off components
            self._power_off_camera()
            self.led_controller.shutdown()
            
            # Set status
            self.status = DeviceStatus.OFFLINE
            
            print(f"[{self.device_id}] Sentry device stopped")
            return True
            
        except Exception as e:
            print(f"[{self.device_id}] Error stopping device: {e}")
            return False
    
    def capture_multispectral(self) -> SentryMeasurement:
        """
        Capture multispectral images with LED illumination.
        
        Returns:
            SentryMeasurement with captured data
        """
        self.status = DeviceStatus.CAPTURING
        
        try:
            # Capture ambient image (no LED)
            ambient_image = self._capture_frame()
            
            # Capture with NIR LED
            self.led_controller.activate_nir()
            time.sleep(0.1)  # Allow LED to stabilize
            nir_image = self._capture_frame()
            self.led_controller.deactivate_nir()
            
            # Small delay between captures
            time.sleep(0.05)
            
            # Capture with Red LED
            self.led_controller.activate_red()
            time.sleep(0.1)
            red_image = self._capture_frame()
            self.led_controller.deactivate_red()
            
            # Create measurement
            measurement = SentryMeasurement(
                timestamp=datetime.now(),
                device_id=self.device_id,
                nir_image=nir_image,
                red_image=red_image,
                ambient_image=ambient_image,
                battery_level=self.battery_level
            )
            
            self.status = DeviceStatus.IDLE
            return measurement
            
        except Exception as e:
            print(f"[{self.device_id}] Error capturing: {e}")
            self.status = DeviceStatus.ERROR
            return None
    
    def process_measurement(
        self,
        measurement: SentryMeasurement
    ) -> SentryMeasurement:
        """
        Process captured measurement on edge device.
        
        Args:
            measurement: Raw measurement data
            
        Returns:
            Processed measurement with NDVI and stress analysis
        """
        self.status = DeviceStatus.PROCESSING
        
        try:
            # Extract spectral channels
            nir_channel = self._extract_channel(
                measurement.nir_image,
                measurement.ambient_image,
                'nir'
            )
            red_channel = self._extract_channel(
                measurement.red_image,
                measurement.ambient_image,
                'red'
            )
            
            # Calculate NDVI on edge
            if self.config.ndvi_calculation_enabled:
                ndvi_result = self.edge_processor.calculate_ndvi(
                    nir_channel,
                    red_channel
                )
                measurement.ndvi_mean = ndvi_result['mean']
                measurement.ndvi_map = ndvi_result['map']
            
            # Detect stress on edge
            if self.config.stress_detection_enabled:
                stress_result = self.edge_processor.detect_stress(
                    ndvi_result['map'] if ndvi_result else None
                )
                measurement.stress_level = stress_result['level']
                measurement.stress_map = stress_result['map']
            
            # Check for alert conditions
            self._check_alert_conditions(measurement)
            
            # Store measurement
            self.last_measurement = measurement
            self.measurement_history.append(measurement)
            
            # Trim history if needed
            if len(self.measurement_history) > 1000:
                self.measurement_history = self.measurement_history[-1000:]
            
            self.status = DeviceStatus.IDLE
            return measurement
            
        except Exception as e:
            print(f"[{self.device_id}] Error processing: {e}")
            self.status = DeviceStatus.ERROR
            return measurement
    
    def _extract_channel(
        self,
        illuminated: Optional[np.ndarray],
        ambient: Optional[np.ndarray],
        channel: str
    ) -> np.ndarray:
        """Extract spectral channel from illuminated image."""
        if illuminated is None:
            return np.zeros((480, 640), dtype=np.float32)
        
        # Convert to grayscale if needed
        if len(illuminated.shape) == 3:
            if channel == 'nir' or channel == 'red':
                gray = illuminated[:, :, 2].astype(np.float32)  # Red channel
            else:
                gray = np.mean(illuminated, axis=2).astype(np.float32)
        else:
            gray = illuminated.astype(np.float32)
        
        # Subtract ambient if available
        if ambient is not None:
            if len(ambient.shape) == 3:
                ambient_gray = np.mean(ambient, axis=2).astype(np.float32)
            else:
                ambient_gray = ambient.astype(np.float32)
            
            gray = np.maximum(gray - ambient_gray * 0.3, 0)
        
        # Normalize
        gray = gray / 255.0
        
        return gray
    
    def _check_alert_conditions(self, measurement: SentryMeasurement) -> None:
        """Check if measurement triggers any alerts."""
        alerts = []
        
        # NDVI alert
        if (measurement.ndvi_mean is not None and
            measurement.ndvi_mean < self.config.alert_threshold_ndvi):
            alert = SentryAlert(
                alert_id=f"{self.device_id}_{datetime.now().timestamp()}",
                timestamp=datetime.now(),
                device_id=self.device_id,
                alert_type="low_ndvi",
                severity="high" if measurement.ndvi_mean < 0.3 else "medium",
                message=f"Low NDVI detected: {measurement.ndvi_mean:.2f}",
                ndvi_value=measurement.ndvi_mean
            )
            alerts.append(alert)
        
        # Stress alert
        if measurement.stress_level > self.config.alert_threshold_stress:
            alert = SentryAlert(
                alert_id=f"{self.device_id}_{datetime.now().timestamp()}",
                timestamp=datetime.now(),
                device_id=self.device_id,
                alert_type="high_stress",
                severity="critical" if measurement.stress_level > 0.85 else "high",
                message=f"High stress detected: {measurement.stress_level*100:.0f}%",
                stress_level=measurement.stress_level
            )
            alerts.append(alert)
        
        # Battery alert
        if measurement.battery_level < self.config.low_power_threshold:
            alert = SentryAlert(
                alert_id=f"{self.device_id}_{datetime.now().timestamp()}",
                timestamp=datetime.now(),
                device_id=self.device_id,
                alert_type="low_battery",
                severity="medium",
                message=f"Low battery: {measurement.battery_level:.0f}%"
            )
            alerts.append(alert)
        
        # Add to alert queue
        self.alert_queue.extend(alerts)
    
    def get_pending_alerts(self) -> List[SentryAlert]:
        """Get all pending unacknowledged alerts."""
        return [a for a in self.alert_queue if not a.acknowledged]
    
    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert."""
        for alert in self.alert_queue:
            if alert.alert_id == alert_id:
                alert.acknowledged = True
                return True
        return False
    
    def enter_sleep_mode(self) -> None:
        """Enter low-power sleep mode."""
        if self.config.sleep_mode_enabled:
            self._power_off_camera()
            self.led_controller.shutdown()
            self.status = DeviceStatus.IDLE
            print(f"[{self.device_id}] Entering sleep mode")
    
    def wake_from_sleep(self) -> None:
        """Wake from sleep mode."""
        self._power_on_camera()
        self.led_controller.initialize()
        self.status = DeviceStatus.IDLE
        print(f"[{self.device_id}] Waking from sleep")
    
    def _capture_frame(self) -> np.ndarray:
        """Capture single frame from camera."""
        # Placeholder: would interface with actual camera
        # Simulate capture
        h, w = self.config.resolution[1], self.config.resolution[0]
        frame = np.random.randint(0, 256, (h, w, 3), dtype=np.uint8)
        return frame
    
    def _power_on_camera(self) -> None:
        """Power on camera."""
        self.camera['initialized'] = True
    
    def _power_off_camera(self) -> None:
        """Power off camera."""
        self.camera['initialized'] = False
    
    def get_status(self) -> Dict:
        """Get device status summary."""
        return {
            'device_id': self.device_id,
            'status': self.status.value,
            'firmware_version': self.config.firmware_version,
            'battery_level': self.battery_level,
            'last_measurement': self.last_measurement.timestamp if self.last_measurement else None,
            'pending_alerts': len(self.get_pending_alerts()),
            'measurements_stored': len(self.measurement_history)
        }


class LEDController:
    """
    LED controller for NIR and Red illumination.
    
    Manages synchronized LED flashing for multispectral capture.
    """
    
    def __init__(
        self,
        nir_power: int = 100,
        red_power: int = 100
    ):
        """
        Initialize LED controller.
        
        Args:
            nir_power: NIR LED power (0-100%)
            red_power: Red LED power (0-100%)
        """
        self.nir_power = np.clip(nir_power, 0, 100)
        self.red_power = np.clip(red_power, 0, 100)
        
        self.nir_active = False
        self.red_active = False
        
        self.total_nir_pulses = 0
        self.total_red_pulses = 0
    
    def initialize(self) -> bool:
        """Initialize LED hardware."""
        # Placeholder: would configure GPIO pins
        print("[LED] LED controller initialized")
        return True
    
    def shutdown(self) -> bool:
        """Shutdown LED hardware."""
        self.deactivate_nir()
        self.deactivate_red()
        print("[LED] LED controller shutdown")
        return True
    
    def activate_nir(self) -> None:
        """Activate NIR LED (850nm)."""
        if not self.nir_active:
            # Placeholder: would set GPIO pin HIGH
            self.nir_active = True
            self.total_nir_pulses += 1
            print(f"[LED] NIR LED ON ({self.nir_power}%)")
    
    def deactivate_nir(self) -> None:
        """Deactivate NIR LED."""
        if self.nir_active:
            # Placeholder: would set GPIO pin LOW
            self.nir_active = False
            print("[LED] NIR LED OFF")
    
    def activate_red(self) -> None:
        """Activate Red LED (660nm)."""
        if not self.red_active:
            # Placeholder: would set GPIO pin HIGH
            self.red_active = True
            self.total_red_pulses += 1
            print(f"[LED] Red LED ON ({self.red_power}%)")
    
    def deactivate_red(self) -> None:
        """Deactivate Red LED."""
        if self.red_active:
            # Placeholder: would set GPIO pin LOW
            self.red_active = False
            print("[LED] Red LED OFF")
    
    def set_nir_power(self, power: int) -> None:
        """Set NIR LED power level."""
        self.nir_power = np.clip(power, 0, 100)
        if self.nir_active:
            # Update PWM duty cycle
            print(f"[LED] NIR power set to {self.nir_power}%")
    
    def set_red_power(self, power: int) -> None:
        """Set Red LED power level."""
        self.red_power = np.clip(power, 0, 100)
        if self.red_active:
            # Update PWM duty cycle
            print(f"[LED] Red power set to {self.red_power}%")
    
    def synchronized_flash(
        self,
        duration_ms: int = 100,
        sequence: List[str] = None
    ) -> None:
        """
        Perform synchronized LED flash sequence.
        
        Args:
            duration_ms: Flash duration in milliseconds
            sequence: Flash sequence ['nir', 'red', 'both']
        """
        if sequence is None:
            sequence = ['nir', 'red']
        
        for led_type in sequence:
            if led_type == 'nir':
                self.activate_nir()
                time.sleep(duration_ms / 1000.0)
                self.deactivate_nir()
            elif led_type == 'red':
                self.activate_red()
                time.sleep(duration_ms / 1000.0)
                self.deactivate_red()
            elif led_type == 'both':
                self.activate_nir()
                self.activate_red()
                time.sleep(duration_ms / 1000.0)
                self.deactivate_nir()
                self.deactivate_red()
            
            # Small delay between flashes
            if led_type != sequence[-1]:
                time.sleep(0.05)
    
    def get_statistics(self) -> Dict:
        """Get LED usage statistics."""
        return {
            'total_nir_pulses': self.total_nir_pulses,
            'total_red_pulses': self.total_red_pulses,
            'nir_power_setting': self.nir_power,
            'red_power_setting': self.red_power,
            'nir_currently_active': self.nir_active,
            'red_currently_active': self.red_active
        }


class EdgeAIProcessor:
    """
    Edge AI processor for on-device NDVI and stress calculation.
    
    Optimized for low-power embedded devices (ARM, ESP32, etc.).
    Uses lightweight algorithms suitable for edge computing.
    """
    
    def __init__(self):
        """Initialize edge AI processor."""
        self.model_loaded = False
        self.processing_count = 0
        self.total_processing_time = 0.0
        
    def calculate_ndvi(
        self,
        nir_channel: np.ndarray,
        red_channel: np.ndarray
    ) -> Dict:
        """
        Calculate NDVI on edge device (optimized).
        
        Args:
            nir_channel: NIR reflectance (0-1)
            red_channel: Red reflectance (0-1)
            
        Returns:
            NDVI results
        """
        start_time = time.time()
        
        # NDVI = (NIR - Red) / (NIR + Red)
        epsilon = 1e-8
        numerator = nir_channel - red_channel
        denominator = nir_channel + red_channel + epsilon
        ndvi_map = numerator / denominator
        
        # Clip to valid range
        ndvi_map = np.clip(ndvi_map, -1.0, 1.0)
        
        # Calculate mean
        valid_pixels = ndvi_map[ndvi_map > 0]
        ndvi_mean = float(np.mean(valid_pixels)) if len(valid_pixels) > 0 else 0.0
        
        # Update statistics
        processing_time = time.time() - start_time
        self.processing_count += 1
        self.total_processing_time += processing_time
        
        return {
            'mean': ndvi_mean,
            'map': ndvi_map,
            'processing_time_ms': processing_time * 1000
        }
    
    def detect_stress(
        self,
        ndvi_map: Optional[np.ndarray],
        threshold: float = 0.5
    ) -> Dict:
        """
        Detect plant stress on edge device.
        
        Args:
            ndvi_map: NDVI values
            threshold: NDVI threshold for stress
            
        Returns:
            Stress detection results
        """
        if ndvi_map is None:
            return {
                'level': 0.0,
                'map': None,
                'stressed_pixels': 0,
                'stress_percentage': 0.0
            }
        
        start_time = time.time()
        
        # Identify stressed pixels (NDVI < threshold)
        stress_mask = ndvi_map < threshold
        
        # Calculate stress intensity
        stress_map = np.where(
            stress_mask,
            1.0 - ndvi_map / threshold,
            0
        )
        
        # Calculate statistics
        total_pixels = ndvi_map.size
        stressed_pixels = np.sum(stress_mask)
        stress_percentage = (stressed_pixels / total_pixels) * 100
        
        # Overall stress level
        stress_level = float(np.mean(stress_map))
        
        processing_time = time.time() - start_time
        
        return {
            'level': stress_level,
            'map': stress_map,
            'stressed_pixels': int(stressed_pixels),
            'stress_percentage': float(stress_percentage),
            'processing_time_ms': processing_time * 1000
        }
    
    def load_lightweight_model(self, model_path: str) -> bool:
        """
        Load lightweight AI model for edge inference.
        
        Args:
            model_path: Path to model file
            
        Returns:
            Success status
        """
        # Placeholder: would load TFLite or ONNX model
        self.model_loaded = True
        print(f"[EdgeAI] Lightweight model loaded from {model_path}")
        return True
    
    def run_inference(self, input_data: np.ndarray) -> np.ndarray:
        """
        Run AI inference on edge device.
        
        Args:
            input_data: Input tensor
            
        Returns:
            Inference output
        """
        if not self.model_loaded:
            print("[EdgeAI] Warning: No model loaded")
            return np.zeros_like(input_data)
        
        # Placeholder: would run actual inference
        # For now, return dummy output
        output = input_data * 0.5
        return output
    
    def get_performance_stats(self) -> Dict:
        """Get edge processing performance statistics."""
        avg_time = (
            self.total_processing_time / self.processing_count
            if self.processing_count > 0 else 0
        )
        
        return {
            'total_processed': self.processing_count,
            'average_time_ms': avg_time * 1000,
            'total_time_seconds': self.total_processing_time,
            'model_loaded': self.model_loaded
        }


class SentryNetworking:
    """
    Network communication manager for Sentry devices.
    
    Handles device discovery, mesh networking, data synchronization,
    and OTA firmware updates.
    """
    
    def __init__(
        self,
        device_id: str,
        protocol: NetworkProtocol = NetworkProtocol.WIFI
    ):
        """
        Initialize networking manager.
        
        Args:
            device_id: Device identifier
            protocol: Network protocol to use
        """
        self.device_id = device_id
        self.protocol = protocol
        
        self.connected = False
        self.peer_devices: Dict[str, Dict] = {}
        self.mesh_enabled = False
        
        self.data_queue: List[Dict] = []
        self.sync_pending = False
        
    def connect(self) -> bool:
        """Connect to network."""
        try:
            # Placeholder: would establish network connection
            print(f"[Network] Connecting via {self.protocol.value}...")
            time.sleep(0.5)
            
            self.connected = True
            print(f"[Network] Connected successfully")
            return True
            
        except Exception as e:
            print(f"[Network] Connection failed: {e}")
            return False
    
    def disconnect(self) -> bool:
        """Disconnect from network."""
        self.connected = False
        print(f"[Network] Disconnected")
        return True
    
    def discover_peers(self, timeout_seconds: int = 10) -> List[Dict]:
        """
        Discover other Sentry devices on network.
        
        Args:
            timeout_seconds: Discovery timeout
            
        Returns:
            List of discovered devices
        """
        if not self.connected:
            print("[Network] Not connected")
            return []
        
        print(f"[Network] Discovering peers (timeout: {timeout_seconds}s)...")
        
        # Placeholder: would perform actual device discovery
        # Simulate finding some devices
        discovered = [
            {
                'device_id': 'sentry_002',
                'ip_address': '192.168.1.102',
                'signal_strength': -55,
                'firmware_version': '1.0.0'
            },
            {
                'device_id': 'sentry_003',
                'ip_address': '192.168.1.103',
                'signal_strength': -62,
                'firmware_version': '1.0.0'
            }
        ]
        
        # Update peer list
        for device in discovered:
            self.peer_devices[device['device_id']] = device
        
        print(f"[Network] Discovered {len(discovered)} peer devices")
        return discovered
    
    def enable_mesh_networking(self) -> bool:
        """Enable mesh networking mode."""
        if not self.connected:
            print("[Network] Cannot enable mesh: not connected")
            return False
        
        self.mesh_enabled = True
        print("[Network] Mesh networking enabled")
        
        # Discover peers for mesh
        self.discover_peers()
        
        return True
    
    def disable_mesh_networking(self) -> bool:
        """Disable mesh networking mode."""
        self.mesh_enabled = False
        print("[Network] Mesh networking disabled")
        return True
    
    def send_measurement(
        self,
        measurement: SentryMeasurement,
        destination: str = "cloud"
    ) -> bool:
        """
        Send measurement data over network.
        
        Args:
            measurement: Measurement to send
            destination: 'cloud' or device_id for mesh
            
        Returns:
            Success status
        """
        if not self.connected:
            # Queue for later
            self.data_queue.append({
                'type': 'measurement',
                'data': measurement,
                'destination': destination
            })
            self.sync_pending = True
            return False
        
        # Serialize measurement (excluding large arrays)
        data = {
            'device_id': measurement.device_id,
            'timestamp': measurement.timestamp.isoformat(),
            'ndvi_mean': measurement.ndvi_mean,
            'stress_level': measurement.stress_level,
            'temperature': measurement.temperature,
            'humidity': measurement.humidity,
            'battery_level': measurement.battery_level
        }
        
        # Send data
        print(f"[Network] Sending measurement to {destination}")
        # Placeholder: would send via HTTP/MQTT/etc
        
        return True
    
    def send_alert(self, alert: SentryAlert) -> bool:
        """
        Send alert over network.
        
        Args:
            alert: Alert to send
            
        Returns:
            Success status
        """
        if not self.connected:
            self.data_queue.append({
                'type': 'alert',
                'data': alert,
                'destination': 'cloud'
            })
            return False
        
        # Serialize alert
        data = {
            'alert_id': alert.alert_id,
            'device_id': alert.device_id,
            'timestamp': alert.timestamp.isoformat(),
            'alert_type': alert.alert_type,
            'severity': alert.severity,
            'message': alert.message
        }
        
        print(f"[Network] Sending {alert.severity} alert: {alert.message}")
        # Placeholder: would send immediately
        
        return True
    
    def sync_queued_data(self) -> int:
        """
        Sync all queued data when connection restored.
        
        Returns:
            Number of items synced
        """
        if not self.connected:
            return 0
        
        synced_count = 0
        
        for item in self.data_queue:
            if item['type'] == 'measurement':
                if self.send_measurement(item['data'], item['destination']):
                    synced_count += 1
            elif item['type'] == 'alert':
                if self.send_alert(item['data']):
                    synced_count += 1
        
        # Clear synced items
        self.data_queue = self.data_queue[synced_count:]
        self.sync_pending = len(self.data_queue) > 0
        
        print(f"[Network] Synced {synced_count} queued items")
        return synced_count
    
    def check_firmware_update(self) -> Optional[Dict]:
        """
        Check for available firmware updates.
        
        Returns:
            Update info if available, None otherwise
        """
        if not self.connected:
            return None
        
        print("[Network] Checking for firmware updates...")
        
        # Placeholder: would query update server
        # Simulate update available
        update_info = {
            'version': '1.1.0',
            'size_kb': 2048,
            'url': 'https://updates.agropulse.com/sentry/1.1.0.bin',
            'release_notes': 'Improved NDVI accuracy, bug fixes',
            'required': False
        }
        
        return update_info
    
    def download_firmware_update(self, update_info: Dict) -> bool:
        """
        Download firmware update.
        
        Args:
            update_info: Update information
            
        Returns:
            Success status
        """
        if not self.connected:
            return False
        
        print(f"[Network] Downloading firmware {update_info['version']}...")
        print(f"[Network] Size: {update_info['size_kb']} KB")
        
        # Placeholder: would download actual firmware
        time.sleep(1.0)  # Simulate download
        
        print("[Network] Firmware downloaded successfully")
        return True
    
    def install_firmware_update(self, firmware_path: str) -> bool:
        """
        Install firmware update (OTA).
        
        Args:
            firmware_path: Path to firmware file
            
        Returns:
            Success status
        """
        print(f"[Network] Installing firmware from {firmware_path}...")
        
        # Placeholder: would install actual firmware
        # This would typically:
        # 1. Verify firmware signature
        # 2. Write to flash memory
        # 3. Set boot flags
        # 4. Reboot device
        
        print("[Network] Firmware installed. Reboot required.")
        return True
    
    def get_network_stats(self) -> Dict:
        """Get network statistics."""
        return {
            'device_id': self.device_id,
            'protocol': self.protocol.value,
            'connected': self.connected,
            'mesh_enabled': self.mesh_enabled,
            'peer_count': len(self.peer_devices),
            'queued_items': len(self.data_queue),
            'sync_pending': self.sync_pending
        }


class SentryScheduler:
    """
    Automated scheduling system for Sentry operations.
    
    Manages periodic measurements, sleep cycles, and optimization
    for battery life.
    """
    
    def __init__(self, device: SentryDevice):
        """
        Initialize scheduler.
        
        Args:
            device: Sentry device to schedule
        """
        self.device = device
        self.schedule: List[Dict] = []
        self.running = False
        
    def add_measurement_schedule(
        self,
        interval_minutes: int,
        start_time: Optional[datetime] = None,
        end_time: Optional[datetime] = None
    ) -> None:
        """
        Add periodic measurement schedule.
        
        Args:
            interval_minutes: Measurement interval
            start_time: Schedule start time (None = now)
            end_time: Schedule end time (None = indefinite)
        """
        schedule = {
            'type': 'measurement',
            'interval_minutes': interval_minutes,
            'start_time': start_time or datetime.now(),
            'end_time': end_time,
            'last_run': None,
            'enabled': True
        }
        
        self.schedule.append(schedule)
        print(f"[Scheduler] Added measurement schedule: every {interval_minutes} minutes")
    
    def add_sleep_schedule(
        self,
        sleep_start_hour: int,
        sleep_end_hour: int
    ) -> None:
        """
        Add daily sleep schedule.
        
        Args:
            sleep_start_hour: Hour to enter sleep (0-23)
            sleep_end_hour: Hour to wake (0-23)
        """
        schedule = {
            'type': 'sleep',
            'sleep_start_hour': sleep_start_hour,
            'sleep_end_hour': sleep_end_hour,
            'enabled': True
        }
        
        self.schedule.append(schedule)
        print(f"[Scheduler] Added sleep schedule: {sleep_start_hour}:00 - {sleep_end_hour}:00")
    
    def run(self, duration_hours: Optional[float] = None) -> None:
        """
        Run scheduler.
        
        Args:
            duration_hours: Run duration (None = indefinite)
        """
        self.running = True
        start_time = datetime.now()
        
        print("[Scheduler] Starting scheduler...")
        
        try:
            while self.running:
                current_time = datetime.now()
                
                # Check if duration exceeded
                if duration_hours:
                    elapsed_hours = (current_time - start_time).total_seconds() / 3600
                    if elapsed_hours >= duration_hours:
                        break
                
                # Process schedules
                for schedule_item in self.schedule:
                    if not schedule_item['enabled']:
                        continue
                    
                    if schedule_item['type'] == 'measurement':
                        self._process_measurement_schedule(schedule_item, current_time)
                    elif schedule_item['type'] == 'sleep':
                        self._process_sleep_schedule(schedule_item, current_time)
                
                # Sleep briefly
                time.sleep(10)  # Check every 10 seconds
                
        except KeyboardInterrupt:
            print("[Scheduler] Interrupted by user")
        finally:
            self.running = False
            print("[Scheduler] Scheduler stopped")
    
    def stop(self) -> None:
        """Stop scheduler."""
        self.running = False
    
    def _process_measurement_schedule(
        self,
        schedule: Dict,
        current_time: datetime
    ) -> None:
        """Process measurement schedule item."""
        # Check if it's time to run
        if schedule['last_run'] is None:
            should_run = True
        else:
            elapsed = (current_time - schedule['last_run']).total_seconds() / 60
            should_run = elapsed >= schedule['interval_minutes']
        
        # Check time window
        if schedule['start_time'] and current_time < schedule['start_time']:
            should_run = False
        if schedule['end_time'] and current_time > schedule['end_time']:
            should_run = False
        
        if should_run:
            print(f"[Scheduler] Executing scheduled measurement")
            
            # Capture and process
            measurement = self.device.capture_multispectral()
            if measurement:
                self.device.process_measurement(measurement)
            
            schedule['last_run'] = current_time
    
    def _process_sleep_schedule(
        self,
        schedule: Dict,
        current_time: datetime
    ) -> None:
        """Process sleep schedule item."""
        current_hour = current_time.hour
        sleep_start = schedule['sleep_start_hour']
        sleep_end = schedule['sleep_end_hour']
        
        # Check if we're in sleep window
        if sleep_start < sleep_end:
            in_sleep_window = sleep_start <= current_hour < sleep_end
        else:  # Crosses midnight
            in_sleep_window = current_hour >= sleep_start or current_hour < sleep_end
        
        # Enter/exit sleep mode
        if in_sleep_window and self.device.status != DeviceStatus.IDLE:
            print(f"[Scheduler] Entering sleep mode")
            self.device.enter_sleep_mode()
        elif not in_sleep_window and self.device.status == DeviceStatus.IDLE:
            print(f"[Scheduler] Waking from sleep")
            self.device.wake_from_sleep()
