# PlatformIO Configuration File for ESP32-CAM
#
# Please visit documentation for the other options and examples
# https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

monitor_speed = 115200

board_build.partitions = huge_app.csv

# Library dependencies
lib_deps =
    # No specific libraries needed for this basic example,
    # as WiFi, esp_http_server, and esp_camera are part of the framework.
